### ISSUE TITLE
🐛 Bug: Husky pre-commit

### ISSUE THREAD

**Issue by preetisharma0123** [Project-Dahlia/Dahlia#112]
### 🐞 What is the bug you are experiencing?

when the initial setup  for husky is done on a Windows Machine, and then one tries to use the husky pre-commit on a mac/Linux machine, there are challenges faced running husky hooks

### 🪜 What are the steps to reproduce this bug?

- Running husky hooks e.g pre-commit gives error; 
- unable to commit with message:
   env: sh\r: No such file or directory
 - No errors but pre-commit hooks not running

### ✅ What is the expected behavior?

Husky hooks run the scrip provided in the hooks. 
In our project the only hook used currently is pre-commit, which runs npx lint-staged script to the staged files before committing.

### 🚫 What is the actual behavior?

Committing any changes to git should run husky pre-commit hook showing any possible lint errors. 

### 🔍 Have you checked to see if this bug has been reported before?

- [X] I checked and didn't find a similar report

**Comment by jaysabe** [comment]
We can close this one, unless you've run into issues since. I was able to get this fixed on my end when I closed #101 .
