### ISSUE TITLE
🐛 Bug: `backend/` linting fails with error when parsing `package.json`

### ISSUE THREAD

**Issue by RickyC0626** [Project-Dahlia/Dahlia#39]
## Suggestion

- Fix lint scripts like so:
```diff
- "lint": "eslint {*.js,json}"
- "lint:fix": "eslint --fix {*.js,json}"
+ "lint": "eslint ."
+ "lint:fix": "eslint --fix ."
```
- Add additional `eslint` rules, similar to the ones in `frontend/`
```json
"rules": {
  "@typescript-eslint/no-unused-vars": "warn",
  "no-undef": "off",
  "@typescript-eslint/no-var-requires": "off"
}
```

**Comment by CeeJayyy007** [comment]
`"rules": {
  "@typescript-eslint/no-unused-vars": "warn",
  "no-undef": "off",
  "@typescript-eslint/no-var-requires": "off"
}`

Considering the above code and since the backend is a Node.js app, is it okay to use TypeScript lint rules or should I search for an alternative?

**Comment by RickyC0626** [comment]
> `"rules": { "@typescript-eslint/no-unused-vars": "warn", "no-undef": "off", "@typescript-eslint/no-var-requires": "off" }`
> 
> Considering the above code and since the backend is a Node.js app, is it okay to use TypeScript lint rules or should I search for an alternative?

Oh right, if we're not using TypeScript in backend, then we can just remove the TypeScript rules.
